### ISSUE TITLE
Support for NoGo Lines

### ISSUE THREAD

**Issue by DJay-X** [naofireblade/homebridge-neato#13]
I will receive my first Neato in a couple of days. The D7 Connected.
And I was happy to see that there is already a Homebridge Plugin.
Thanks for your work and sharing. 👍🏻
I'll give some feedback when my Neato has arrived and is connected. 😃

**Comment by naofireblade** [comment]
That would be great. Thanks!

**Comment by Be2daErtin** [comment]
I'm wondering if the app acts as the brain for the robot. I.e where it should and should not go. I got my D7 as well. Read something about it using beehive for maps..... Will check it out.

**Comment by naofireblade** [comment]
Thanks for the detailed report and the screenshots.
1. I will look into the no-go-lines. That will require an update of the underlying botvac node.
2. This is due to a limitation of the neato api. I cannot set or read the eco mode via the api. I just can start the cleaning process with eco mode on/off. Therefore the switch in homebridge is asynchronus to the neato app. But I think the neato app remembers the mode after starting a cleaning process.

**Comment by DJay-X** [comment]
@naofireblade Thanks for the time you are investing.
It would be fantastic if I could start Neato D7 with HomeKit (Siri) with the clean switch, and the Neato would just start in its default setting which is always eco in the neato App. 
Thanks in advance.

**Comment by naofireblade** [comment]
I had no time for this yet. If anybody is able to code js, I would appreciate a pull request :) .

**Comment by DJay-X** [comment]
@naofireblade Unfortunately it looks like you are still the man of the hour. ;) Hopefully you'll find some time in the near future for ongoing development in regard of the no-go-lines.
Thanks again for considering this.

**Comment by naofireblade** [comment]
Still waiting for the firmware update with no-go-lines that is scheduled for "fall 2018" :/ .

**Comment by ifeign** [comment]
I was just on the phone with Neato support for something unrelated, but the rep mentioned that they just released the no-go line update for the D5 today.

**Comment by naofireblade** [comment]
Yes yes yes :) . I got a mail also but had no update available in the app last night. And no firmware file to download on the website. I will check it again today.

**Comment by naofireblade** [comment]
My D5 finally got the update. He‘s discovering my home right now. I hope I will find some spare time to update the plugin and the node api in the next 2 weeks.

**Comment by ifeign** [comment]
Yay! I hope you can figure it out.

**Comment by naofireblade** [comment]
It's working pretty well in my development environment already. I will fix some more stuff in this release:
- setting care-navigation and nogolines in the home app instead of the config file
- loading eco-mode, care-navigation and nogolines options from the last run (so the options should be consistent if you switch between using the neato app and the home app)

**Comment by ifeign** [comment]
Wonderful! I was worried that the no-go lines wouldn't work with Homebridge
because it seemed so tied to the Neato app itself. Glad I was wrong.

**Comment by DJay-X** [comment]
Can't wait. Thanks @naofireblade 
And I hope it will also work with my D7. After you release the latest Version, I immediately will give a try. :)

**Comment by alecc131** [comment]
Awesome! When will this be pushed to npm?

**Comment by naofireblade** [comment]
I completed the new version yesterday and had to wait for my pull request of the node api to be merged and pushed to npm as well. That happened now and I can push my plugin this evening.

**Comment by naofireblade** [comment]
The plugin is now published to npm in version 0.5.0.

**Comment by ifeign** [comment]
Awesome! I'm going to test it out.

**Comment by DJay-X** [comment]
Awesome! I already tested it. ;) 
First, thanks a lot @naofireblade Really helps a lot not with starting Neato by calling Siri and the D7 runs as always mit no-go lines. 
Looks great all-in-all. Works with my BotVacD7Connected', firmware: '4.2.3-153

What I noticed is just some delay (rings) after I start, pause or send Neato back to the dock. 
Not sure if this "okay" and meant to be. 

![napkin 15 11 18 7 31 23 pm](https://user-images.githubusercontent.com/3874239/48573614-10c51c00-e90d-11e8-8fd3-8a62e3f19570.png)

**Comment by naofireblade** [comment]
The long output in the journal is my bad, i accidentally left a console log in the node api. I made a pull request to fix that.

There should be only one ring on the action you perform (e.g. start cleaning) for about 2 seconds until the robot starts. How long do you have these rings? Do they occur after every command or just sometimes?

Do you have set the "refresh" parameter? If not, no updates should after cleaning is done. Let's wait until the node api update is pushed and I can update my plugin. Then it would be very helpful if you could start the plugin in debug mode.

**Comment by naofireblade** [comment]
Ok I released 0.5.1 to get rid of the long console log. Could you please start homebridge with this option to further investigate your problems? `DEBUG=homebridge-neato`

**Comment by naofireblade** [comment]
You're welcome. I'm glad it's working well. I will close this and reopen it if any problems with the no go lines occur.
