### ISSUE TITLE
Neato App on IOS fails when plugin is used

### ISSUE THREAD

**Issue by Supp0rtLinux** [naofireblade/homebridge-neato#17]
I have a D3. With the plugin installed, everything works fine. But my ability to use the app from my iPhone now fails. Prior to the homebridge-neato plugin, I could start the app and connect to the D3 from anywhere (home or out and about using 3g/4g/LTE). I also got notifications on my phone when cleaning completed and an updated coverage map. With the homebridge plugin enabled, I can control it from the Home app in IOS, but not from the Neato app. Further, while it cleans, etc I get no notifications when cleaning is done or maps (which are tied to the IOS app). Is there a login limitation? I know with Arlo's you can only connect from the app or the plugin, not both at the same time. Is there something similar with this plugin? Are others experiencing the same issue?

**Comment by ifeign** [comment]
I've noticed this too, and it happens even when I don't use Homekit to turn on my D7. The wifi indicator will flash for quite a while, until it then goes solid and re-establishes its connection to the Neato app. The Vacuum remains responsive in Homekit though.

**Comment by naofireblade** [comment]
I'm not sure that this is realted to the plugin. I use the plugin and the app at the same time for over a year now. First with a Botvac Connected and now a Botvac Connected D5.
Does the problem dissolves as soon as you stop homebridge (or remove the plugin from homebridge).

**Comment by DJay-X** [comment]
I can't confirm any issues using the plugin and the Neato App with my D7. Controlling with Plugin/HomeKit and App works together here. Including all notifications. 
I use the plugin from the first day on and also the Neato App on iOS.
Firmware on the D7 always the latest. Now @4.2.3-153

The only thing I noticed, but this has nothing to do with the plugin, that the Neato from time to time loses Wifi connection but after a few seconds all is back to normal. 

@naofireblade Hope you are already received also the firmware update for your D5 with no-go lines. 
I noticed that the problem starting the Neato from the app always "without" no-go lines, is probably an issue or not supported by Neato and not by your plugin. If I start the Neato with IFTTT the same happens. Always starts without no-go lines. :( 
But more this ongoing here. ;) https://github.com/naofireblade/homebridge-neato/issues/13

**Comment by ifeign** [comment]
It appears to work fine now that I've reset the wifi settings on my D7.

**Comment by PelagicDev** [comment]
Sorry to piggy-back on this issue, but can someone tell me how to actually add my D7 to the home app? I've got the plugin installed and the log said that it found my D7 Robot so I think everything is good there.

I'm just unsure if I need to wait for Homekit to sync with homebridge or if there is sommething additional I need to do to add my D7 robot to the Home app. Thanks!

**Comment by ifeign** [comment]
Restart your Homebridge.

**Comment by ifeign** [comment]
Yes, please post your config without any personal info. This is a very simple plugin to use, mine looks like this:

```
        {
            "platform": "NeatoVacuumRobot",
            "email": "email@website.com",
            "password": "password"
        }
```
You'll need to ensure your D7 is registered with your Neato account first.

**Comment by naofireblade** [comment]
> I've noticed this too, and it happens even when I don't use Homekit to turn on my D7. The wifi indicator will flash for quite a while, until it then goes solid and re-establishes its connection to the Neato app. The Vacuum remains responsive in Homekit though.

I can confirm this behavior now. While cleaning the app can't connect to the robot. About 60s after cleaning, the app can establish a connection again.
I have 4 systems that connect to the robot and so I might reach the limit: Homekit, Home Assistant, Alexa, Neat App.

**Comment by naofireblade** [comment]
The newest release [v0.5.0](https://github.com/naofireblade/homebridge-neato/releases/tag/v0.5.0) has an option to use the refresh mode "auto" (updates the robot state only while cleaning) or to disable background refreshes completly with `"refresh": 0`.
