### ISSUE TITLE
Can not add robot to homekit

### ISSUE THREAD

**Issue by satimo275** [naofireblade/homebridge-neato#18]
plugin installation and config are probably clean. Homebridge starts without error and also the homematic plugin goes. Can not add robot to homekit. What can this be?

**Comment by satimo275** [comment]
Now the Neato ist available in Honekit but the switches are not really working....step by step :-)

**Comment by naofireblade** [comment]
Hey, what did you change to make it work? Others might find that helpful.
Do the switches show loading circles now? Or are they unavailable?
