### ISSUE TITLE
More than one robot

### ISSUE THREAD

**Issue by CooperCGN** [naofireblade/homebridge-neato#2]
Any chances you're going to support more than one robot?

**Comment by naofireblade** [comment]
Sure, I will look into that.

**Comment by CooperCGN** [comment]
That would be awesome, glad I found your plugin :-)

**Comment by naofireblade** [comment]
Hey I just added support for multiple robots in version 0.4.0. You can update it with 
> npm update -g homebridge-neato

To be compatible with the recent update you have to adapt your config:
```json
"platforms": [
	{
		"platform": "NeatoVacuumRobot",
		"email": "YourEmail",
		"password": "YourPassword",
		"refresh": "0"
	}
]
```
I would like to hear if it's working for you :) .

**Comment by CooperCGN** [comment]
Works perfectly. Thank you so much!

**Comment by naofireblade** [comment]
Great, thanks for your feedback.
