### ISSUE TITLE
Support for zone cleaning

### ISSUE THREAD

**Issue by ifeign** [naofireblade/homebridge-neato#20]
I’m sure you were expecting to see somebody request this, but now that the zone cleaning update for the D7 is live, would it be possible to create HomeKit switches for each named zone?

I know you don’t have a D7, so testing it will be an issue.

**Comment by DJay-X** [comment]
Would love to see this as well in one of the next updates. 😍
Imagine... "Hey Siri, go clean the Kitchen" 😅

Just to mention, Zone cleaning works great here with D7 after the update by using the Neato App.
But it's of course still 5 clicks to get a zone cleaned. 

![napkin 05 12 18 6 58 43 pm](https://user-images.githubusercontent.com/3874239/49533650-dcb39a00-f8bf-11e8-947e-2c77b118f8dc.png)

**Comment by bubez81** [comment]
would be awesome!

**Comment by naofireblade** [comment]
The [developer documentation](https://developers.neatorobotics.com/api/robot-remote-protocol/housecleaning) currently gives a hint that zone cleaning is possible but does not lists the required params and explanation. I mailed the neato team and asked them to update the documentation.

**Comment by matrosovas** [comment]
@naofireblade any feedback from them?

**Comment by naofireblade** [comment]
Yes I got a response and they updated the documentation. I have an idea how to implement this in homekit  but it requires some time.

**Comment by ifeign** [comment]
Looks like @az0uz generously created a PR to add this functionality, however it is currently being held up over at the node-botvac repo, because of something to do with the readme file. I wish I were a little more knowledgeable about Homebridge plugins so that I could offer some form of help, but currently the ball is in @az0uz's court.

**Comment by DJay-X** [comment]
Ah.. that's it. I was wondering why zone cleaning is still not available. Would be great to see it in @naofireblade 's great plugin. It's a while now. Very looking forward to it.

**Comment by DJay-X** [comment]
@naofireblade Any news on this? If it’s not your direct influence maybe you can push somebody in the right direction so that this feature does not stop here. Thanks again. 👍🏻

**Comment by ifeign** [comment]
@DJay-X If you look at the pull request https://github.com/naofireblade/homebridge-neato/pull/28 You'll see that we're waiting for another pull request to get merged on node-botvac

**Comment by ifeign** [comment]
Node-botvac just merged the necessary PR! Zone cleaning should now be able to be merged into this plugin!!
