### ISSUE TITLE
No-go-Lines not working when starting trough homekit (D3)

### ISSUE THREAD

**Issue by linusnyren** [naofireblade/homebridge-neato#21]
Hi! great work with the plugin!
The D3 got an update earlier this week which added no go lines functionality.
But when started trough the plugin the no go lines isnt activated.
I see that the D5 had the same problem earlier so maybe its just a small correction needed?

Cheers Linus!

**Comment by naofireblade** [comment]
Do you have the most recent version v0.5.1 of this plugin installed? Did you switch "No Go Lines" on in homekit?

**Comment by lobbin** [comment]
I was about to open a new issue, asking if it was possible to configure the neato plugin to always use no go lines, as I would like to hide the switch, but still use it.

**Comment by naofireblade** [comment]
I‘m closing this because the issue author did not respond. I created issue #31 for your feature request @lobbin
