### ISSUE TITLE
[NeatoVacuumRobot] Could not find robot_serial for specified vendor_name: [object Object]

### ISSUE THREAD

**Issue by allenbf** [naofireblade/homebridge-neato#22]
This plugin was working fine as of last night, today I am not able to start the Neato in the Home app and looking at Homebridge, this is the error I see.  Am I missing something?

[NeatoVacuumRobot] Could not find robot_serial for specified vendor_name: [object Object]

Thanks for your help!

**Comment by allenbf** [comment]
Disregard! Rookie error, my Neato was offline. Posting in case another rookie needs this :-)

**Comment by naofireblade** [comment]
Thanks for clarifying this issue :)
