### ISSUE TITLE
D7 Connected no battery info

### ISSUE THREAD

**Issue by bubez81** [naofireblade/homebridge-neato#24]
Hello, great job. 
It's strange but I can't see the battery status of my D7 Connected (Battery - Not supported)

**Comment by DJay-X** [comment]
Never had an eye on the battery level of my D7. But there is one. ;)
Here it seems to work.
homebridge@0.4.46 | node@11.10.0 | npm 6.8.0 | n@2.1.12 | neato@0.5​.1

![napkin 2 27 02 19 10 39 13 pm](https://user-images.githubusercontent.com/3874239/53524982-15d76100-3ae1-11e9-9ec0-00562b0b655a.png)
