### ISSUE TITLE
First-timer for Node and Homebridge - homebridge_neato installation

### ISSUE THREAD

**Issue by oddeonetwerx** [naofireblade/homebridge-neato#25]
I'm usually fairly tech savvy, but this is my first time with node or homebridge. I have managed to get everything installed, but I'm stuck on the step where I need to find my config file. I cannot find it. Can somebody possibly help me with this stuff?

**Comment by oddeonetwerx** [comment]
I found the config file in the homebridge folder...maybe that is the one...

I updated it's name to config.json, left it in the homebridge folder and updated the file to:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "NeatoVacuumRobot",
            "name": "Neato of Love"
        }
    ],

    "platforms": [
        {
            "platform": "NeatoVacuumRobot",
            "email": "oddeonetwerx@gmail.com",
            "password": "Permofryed25"
        }
    ]
    ]
}


Still when I scan the homebridge barcode with my HomeKit app, it says Accessory not found.

**Comment by oddeonetwerx** [comment]
I changed the config file name to config.json, left it in the homebridge folder and updated the file to this:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "NeatoVacuumRobot",
            "name": "Neato of Love"
        }
    ],

    "platforms": [
        {
            "platform": "NeatoVacuumRobot",
            "email": "my email",
            "password": "my password"
        }
    ]
    ]
}


Still, when I can the homebridge barcode with my HomeKit, is says accessory not found.

**Comment by oddeonetwerx** [comment]
Seems like I might be getting closer, but still an error:

homebridge
[3/2/2019, 2:17:56 PM] Loaded config.json with 1 accessories and 1 platforms.
[3/2/2019, 2:17:56 PM] ---
[3/2/2019, 2:17:56 PM] Loaded plugin: homebridge-neato
[3/2/2019, 2:17:56 PM] Registering platform 'homebridge-neato.NeatoVacuumRobot'
[3/2/2019, 2:17:56 PM] ---
[3/2/2019, 2:17:56 PM] Loading 1 platforms...
[3/2/2019, 2:17:56 PM] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[3/2/2019, 2:17:56 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'NeatoVacuumRobot' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by DJay-X** [comment]
@oddeonetwerx 
I hope you have found a solution. 
Otherwise this could help, if Neato plugin is the only platform you use and have no accessories.

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [],
	"platforms": [{
		"platform": "NeatoVacuumRobot",
		"email": "YOURNEATOEMAILADRESS",
		"password": "YOURNEATOPASSWORD",
		"refresh": "60"
	}]
}
```


Anyway, this is not the right place for general/basic Homebridge questions and support. Your Issue does not have anything to do with the neato plugin.
Please visit https://www.reddit.com/r/homebridge/ to ask the community if you are on English language and https://forum.smartapfel.de if you are on German language.

Enjoy and good luck.

**Comment by naofireblade** [comment]
Thank you @Djay-X for helping the users :) .
