### ISSUE TITLE
Only clean switch active

### ISSUE THREAD

**Issue by jenscolt** [naofireblade/homebridge-neato#27]
Hello,

I am attempting to get my new neato D4 connected on my homebridge.  I was able to add the platform to the config.json file (with the disable code line) and run home bridge.  I am also able to see the clean switch.  The clean switch works flawlessly and starts and pauses cleans without issue.  From what I can tell I am also supposed to be able to see other switches and sensors.  Siri commands to send to dock or get battery level are unrecognized.  

Is there an additional step I am missing or something else I need to do to get this set up correctly?

Thanks in advance for the help and thanks for making such a useful plugin

**Comment by ifeign** [comment]
Post your config. Have you set up your D4 in the Neato app with no-go lines or a map of your house?

**Comment by jenscolt** [comment]
Here's my config.  The D4 is set up with no-go lines.  I have it on an automation that runs when the last person leaves the house.  It runs great and according to the no-go lines I've set up.

{
    "bridge": {
        "name": "Homebridge",
        "username": "<my-mac-address>",
        "port": 51825,
        "pin": "031-54-154"
    },

    "accessories": [
        {
            "accessory": "Http",
            "name": "Theater Curtains",
                "on_url": "http://XXX/1",
                "off_url": "http://XXX/0",
                "http_method": "GET"
        },
        {
                "accessory": "MagicHome",
                "name": "Trim Lights",
                "ip": "<IP>",
                "setup": "GRB",
                "purewhite": false
        },
        {
                "accessory": "MagicHome",
                "name": "Cabinent Lights",
                "ip": "<IP>",
                "setup": "RGBW",
                "purewhite": false
        },
        {
                "accessory": "MagicHome",
                "name": "Piano Lamp",
                "ip": "<IP>",
                "setup": "RGBW",
                "purewhite": false
        },
	{
		"accessory": "MagicHome",
		"name": "Shelf Lights",
		"ip": "<IP>",
		"setup": "RGBW",
		"purewhite": false
	}
        ]

    "platforms": [
    	{
	"platform": "NeatoVacuumRobot",
	"email": "<my-email>",
	"password": "<my-password>,
	"disabled":["dock","dockstate","eco","nogolines","extracare","schedule"]
    	}	
    ]

}

**Comment by ifeign** [comment]
There's your problem, you copied the entire sample config. Delete the entire line that says "disabled"

**Comment by naofireblade** [comment]
As @ifeign said, you had the line for disabling some switches and sensors in your config.

@ifeign I really appreciate your help with the issues here. Thanks!

**Comment by jenscolt** [comment]
I suppose that should have been obvious.  Thanks for my help, I really appreciate it
