### ISSUE TITLE
Issue with config.json file

### ISSUE THREAD

**Issue by sether82** [naofireblade/homebridge-neato#29]
I followed the instructions and I keep getting "There was a problem reading your config.json file."

My Neato portion of the config looks like this (some surrounding sections included for formatting):

"ringing": {
	"event": "single",
	"motion": false,
	"contact": false
  }
},
{
       "platform": "NeatoVacuumRobot",
       "email": "myemail",
       "password": "mypassword"
    }
{
   		"platform": "Nest",

I don't know if this makes a difference but I had to use "sudo npm install -g --unsafe-perm homebridge-neato" when installing the plug in. I did the same thing to install Homebridge and the two other working platforms I have. This is the only way I can get homebridge and its platforms installed for some reason. Could that be the problem? I don't understand what I'm doing wrong, why it says there was a problem with my config.

**Comment by DJay-X** [comment]
Have you checked your entire config.json on jsonlint.com to be sure it's working properly? With a quick look just on your posted lines there could be something wrong, missing a comma.

```
{
"platform": "NeatoVacuumRobot",
"email": "myemail",
"password": "mypassword"
},
```

**Comment by sether82** [comment]
That did it. Thank you very much!
