### ISSUE TITLE
Botvac D5 is always put into 'extra-care' mode when started.

### ISSUE THREAD

**Issue by CooperCGN** [naofireblade/homebridge-neato#3]
It's me again. ;)

I guess it has something to with the payload posted to the neato cloud. I tried to figure it out on my own but as I am a total JS noob, maybe you can point me to where the specific call is made to start the robot.

I had the same problem with a php script, there I had to alter a parameter called navigationMode from 2 to 1.

thanks for your help

**Comment by naofireblade** [comment]
Hey welcome back. Thanks for the feedback.

I will add a switch to set extra care mode on/off. But before I can do that I need to enhance the underlying node-botvac so that I can determine if it is a D5 or not. Because users with an older robot shouldn't see a switch that is useless for them. This might take some days.

Meanwhile, if you want to default it to navigationMode 1, it's on line 159 of index.js
Just replace it with this line:

`that.robot.startCleaning(that.robot.eco, 1, callback);`

**Comment by naofireblade** [comment]
I got another idea. Maybe its sufficient to set this in the config? This way you can't change it in the ui but the setting will be preserved after a homebridge restart.

**Comment by CooperCGN** [comment]
Well, I think for me that would be sufficient as I have two D5 running in my home. I have no idea how that would affect people with two different robots. I actually would prefer the settings thing, homekit is already cluttered by Neato switches (the D5 for example doesn't even have an eco/turbo mode).

**Comment by naofireblade** [comment]
Oh I didn't know that they removed a feature from the old Botvac Connected on the newer models. Ok in the first update I will add a config parameter for care navigation. And later on I will make the eco/turbo switch model dependent.

**Comment by CooperCGN** [comment]
Neato still considers the Botvac Connected as their top of the range model although they improved some internal things for the D5 - maybe they need to sell them off due to high stock ;)
The D5 has Start/Stop/Pause with optional extra-care (that means no bumping into furniture) and a spot clean mode (with the option doing the area twice and/or extra-care).

**Comment by naofireblade** [comment]
I released version 0.4.1 with a config parameter for extraCareNavigation. Default ist off now, if you want to enable extraCareNavigation just set the parameter `"extraCareNavigation" : true` .
