### ISSUE TITLE
Change icon in homekit

### ISSUE THREAD

**Issue by jrcharles** [naofireblade/homebridge-neato#30]
Hello,

Is there a way to change the icon in HomeKit?  It currently just shows up as a switch. 
![B0A2FBB8-451C-466D-BD11-9170F94FBBE1](https://user-images.githubusercontent.com/29494771/58218442-df227880-7cd4-11e9-995a-56e83e44af84.jpeg)

**Comment by ifeign** [comment]
Not to anything worthwhile, there is no official vacuum icon (or official support for vacuums for that matter).

**Comment by naofireblade** [comment]
Hey jcharles. The icon is assigned in each HomeKit app by the type of the device. HomeKit currently does not support vacuum robots. Therefore I implemented the reboots functions as switch devices and you see a switch icon.

Some apps do support a wider set of icons to choose from but not even the great Eve app has a vacuum robot icon yet.
