### ISSUE TITLE
Status inconsistencies / homebridge crash

### ISSUE THREAD

**Issue by theseiman** [naofireblade/homebridge-neato#32]
I‘m using your great plugin version 0.5.2 with my Neato Botvac D3 Connected, Software-Version 4.4.0-72. I see all triggers in HomeKit and I‘m able to start/stop the D3 as well as sending it back to the dock. So far, so good.

I‘ve set up no-go lines, extra care and turbo-mode in the Neato app (Version 2.8.2 on an iPhone X, iOS 12.3.1) but the status is not reflected at the corresponding HomeKit tile. And even worse: As soon as I make changes in the Neato app (i.e. disabling the extra care) or enabling a feature in HomeKit (like no-go lines, which supposed to be activated already) the whole homebridge seems to crash. All accessories (connected through homebridge) in HomeKit show an exclamation mark. After restarting the homebridge service, everything works again, besides the issue described above.

I really appreciate how much work you put in this plugin! Hope you can help me with my problem. My config looks like this:

...
        },
        {
            "platform": "NeatoVacuumRobot",
            "email": "myemailaddress",
            "password": "mypassword",
            "refresh": "60"
        },
        {
            "platform": "Fritz!Box",
...

**Comment by ifeign** [comment]
Set the refresh to 0

**Comment by theseiman** [comment]
I‘ve set the refresh parameter to „0“. Still the same behavior.

**Comment by ifeign** [comment]
Could you post your full config?

**Comment by naofireblade** [comment]
Do you still experience this issue? Can you post your (anonymized) config and log output?

**Comment by naofireblade** [comment]
Closing for now. Will reopen if log output is provided.
