### ISSUE TITLE
Neato D3 HomeKit

### ISSUE THREAD

**Issue by z3r0-beep** [naofireblade/homebridge-neato#34]
Hi naofireblade,

i've installed your Neato Plugin with all dependencies and updated the Config.json with the Platform Block, including my Credentials from the Neato Account.
But it doesn't Show up in HomeKit.
Tried some Reboots and reinstalled everything again, but it's still the same.
Maybe you can Help me here? Would be much appreciated!

Thanks!

**Comment by ifeign** [comment]
Post your config

**Comment by z3r0-beep** [comment]
Nevermind, found the error.
Should Update the correct config.json! ;)
Sorry for stealing your time and thanks for the hard work on your Plugin!
