### ISSUE TITLE
Homebridge crashes when 2 zones have the same name

### ISSUE THREAD

**Issue by DJay-X** [naofireblade/homebridge-neato#37]
Hey there.
Thanks @naofireblade and at all participant developers. Great update to @0.6.0.
Love Zone cleaning. [♥]
https://forum.smartapfel.de/forum/thread/1408-homebridge-neato-f%C3%BCr-neato-botvac-connected-saugroboter/?postID=61703#post61703

A suggestion for a next update. At the moment when there is a duplicate in the Neato app with the room name, the plugin has a problem with this. In my case my floor plan has two rooms with the identical name "Flur".
After I renamed one of the rooms into "Flur klein", to have a "Flur" and a "Flur klein", the plugin works perfect. Maybe tthis info helps.

Thanks again guys for the time you are investing, your great work and ongoing development.

`Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Found robot #1 named "Robbi" with serial "xxxxxxx-xxxxxxx"
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Wohnzimmer
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Schlafzimmer
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Esszimmer
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Küche
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Flur
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Badezimmer
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Adding zone cleaning for: Flur
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Wohnzimmer'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Schlafzimmer'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Esszimmer'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Küche'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Flur'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Badezimmer'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] Initializing platform accessory 'Robbi - Flur'...
Jul 15 15:23:11 raspberrypi-3BPlus homebridge[449]: [2019-7-15 15:23:11] [NeatoVacuumRobot] error getting boundaries: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: xxxxx-xxxx-xxxx-xxxx-xxxxx: undefined`

**Comment by naofireblade** [comment]
This should be fixed in v0.6.3. @DJay-X can u test this again maybe?

**Comment by DJay-X** [comment]
@naofireblade Update works reliable with my D7. Zone Cleaning buttons for every defined room are available. Also can be placed in separate rooms if preferred. No Issue with Naming.
Only point I noticed is that in the log is an entry after starting D7 
`[NeatoVacuumRobot] Error, robot is already cleaning`
But this doesn't effect homebridge running and the Neato is doing its work, finishing and going back to dock noticed by Homebridge.
I appreciate your work and time you are investing. 👍 

```
Aug 15 09:06:53 raspberrypi-3BPlus homebridge[23413]: [2019-8-15 09:06:53] [NeatoVacuumRobot] Error, robot is already cleaning
Aug 15 09:06:53 raspberrypi-3BPlus homebridge[23413]: [2019-8-15 09:06:53] [NeatoVacuumRobot] Error, robot is already cleaning
Aug 15 09:06:53 raspberrypi-3BPlus homebridge[23413]: [2019-8-15 09:06:53] [NeatoVacuumRobot] Error, robot is already cleaning
Aug 15 09:06:53 raspberrypi-3BPlus homebridge[23413]: [2019-8-15 09:06:53] [NeatoVacuumRobot] Error, robot is already cleaning
Aug 15 09:06:53 raspberrypi-3BPlus homebridge[23413]: [2019-8-15 09:06:53] [NeatoVacuumRobot] Error, robot is already cleaning
Aug 15 09:06:53 raspberrypi-3BPlus homebridge[23413]: [2019-8-15 09:06:53] [NeatoVacuumRobot] Error, robot is already cleaning
```

**Comment by naofireblade** [comment]
Thank you very much for your testing time :)
