### ISSUE TITLE
Zone cleaning always starts with Turbo on, even if default option is Eco

### ISSUE THREAD

**Issue by DJay-X** [naofireblade/homebridge-neato#39]
I noticed that when zone cleaning now is triggered by HomeKit, the Turbo mode is always on, even when in Neato App default option is checked Eco.

Do I miss something in the config or maybe a bug?

Thanks again. :)

**Comment by DennisFury** [comment]
Happening here too.  Eco Mode and Extra Care settings do not actually turn on. I'll flip the switches on in HomeKit, then close/reopen Neato app and those 2 settings remain off.

**Comment by DJay-X** [comment]
@naofireblade Hope you are doing well. Any news on this Bug for a next release? 🥰 Thx

**Comment by naofireblade** [comment]
Hey @DJay-X thanks for asking. Yes I'm doing great. Your problem should be fixable this week, while drinking my 2 coffee from an awesome anonymous donor. :blush:

The problem from @DennisFury is not fixable. The Neato API does not allow setting these options. I can only pass the options when starting a cleaning.
Therefore I cache the options in homekit and use them as parameters for the next cleaning.

**Comment by naofireblade** [comment]
Fixed in v0.7.0
