### ISSUE TITLE
Hide switch for eco/turbo on not compatible models (D3, D5)

### ISSUE THREAD

**Issue by naofireblade** [naofireblade/homebridge-neato#4]

**Comment by EdiVip** [comment]
Is any option to put possibility to disable some switches in configuration file? For example I want to have only "Power on" Button

**Comment by naofireblade** [comment]
Sounds good, I created a new issue for that and will try to implement that on the upcoming weekend.

https://github.com/naofireblade/homebridge-neato/issues/5

**Comment by naofireblade** [comment]
Workaround with #5
