### ISSUE TITLE
Can‘t switch off No-Go lines

### ISSUE THREAD

**Issue by Krocko** [naofireblade/homebridge-neato#41]
If i switch off the No-Go lines switch in the Home app and reopen the Home app, the switch is on again.

**Comment by naofireblade** [comment]
That's intended. Neato offers no API to switch the feature on or off outside of the official Neato app. Therefore you can set it only temporary in the homekit app and start the cleaning immediately afterwards.

When you close the app and reopen it, all settings will be loaded again from the neato server.
