### ISSUE TITLE
Zone cleaning switches don't have settings

### ISSUE THREAD

**Issue by jrkmtf** [naofireblade/homebridge-neato#43]
I've noticed that the switches to represent my zones don't have a settings page in the Home app.  The result of this is that I cannot group these with the rest of the Neato device, place them in any room other than "Default Room", or remove them from my Favorites.  Ideally, I would like to hide these from Homekit altogether via my config.json file.  At the very least, sorting them into the appropriate room or grouping them with the Neato would go a long way to reducing clutter in my Home app.

**Comment by naofireblade** [comment]
They should have a settings page because they are different accessories. Can you check the eve app if you can sort them to different rooms there?

**Comment by naofireblade** [comment]
Will be closed until further information can be provided. Feel free to reopen any time.
