### ISSUE TITLE
Possibility to change the prefix "Clean The" in zone mode

### ISSUE THREAD

**Issue by bubez81** [naofireblade/homebridge-neato#45]
Hello, I'm very happy with this plugin, but it would be great if there was the possibility to change the prefix of the various zone from "Clean the" to "personal prefix". In my language sounds better "Pulisci" instead of "Clean the"
I know that I can change the name directly in the iPhone app but sometimes I have to reset the configuration and I have to change everything every time.

**Comment by DennisFury** [comment]
Change the command to whatever you want within Apple's "Home" app. Find the switch, go to the settings, and change the title.  I have mine titled like "the vacuum and Clean the Den", so I can say "Hey Siri, turn on the vacuum and clean the Den"

**Comment by naofireblade** [comment]
Thanks for the answer @DennisFury . I think that should fix the issue.
