### ISSUE TITLE
Robot doesn't show

### ISSUE THREAD

**Issue by maydaydarkhorse** [naofireblade/homebridge-neato#46]
Hi,

I did have this sort of working using 0.6.3 but it was flakey - so I thought I would try the Beta (Now 0.7.0-11) and my vacuum has disappeared.  I am no home bridge or Linux wizard though so any help would be appreciated!

**Comment by naofireblade** [comment]
Hi, what Robot do u use? Does it maybe show in another room? Can you provide homebridge logs from the startup?

**Comment by chrisaiello** [comment]
I'm just setting up homebridge-neato for the first time, and I'm not seeing any devices show up in the home app. Not sure if it's an error on my part or not. I've followed the 'simple' configuration on the main page, this is what my startup log looks like:

`
[10/12/2019, 7:09:27 PM] Loaded config.json with 0 accessories and 2 platforms.
[10/12/2019, 7:09:27 PM] ---
[10/12/2019, 7:09:27 PM] Loaded plugin: homebridge-neato
[10/12/2019, 7:09:27 PM] Registering platform 'homebridge-neato.NeatoVacuumRobot'
[10/12/2019, 7:09:27 PM] ---
[10/12/2019, 7:09:27 PM] Loaded plugin: homebridge-tcc

[10/12/2019, 7:09:28 PM] Registering platform 'homebridge-tcc.tcc'
[10/12/2019, 7:09:28 PM] ---
[10/12/2019, 7:09:28 PM] Loading 2 platforms...
[10/12/2019, 7:09:28 PM] [Thermostat] Initializing tcc platform...
[10/12/2019, 7:09:28 PM] [Thermostat] Logging into tcc...
[10/12/2019, 7:09:28 PM] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[10/12/2019, 7:09:28 PM] [NeatoVacuumRobot] Refresh is set to: auto
[10/12/2019, 7:09:29 PM] [Thermostat] Logged into tcc! [ { deviceID: '5192195',
    name: 'Thermostat',
    usePermanentHolds: false } ]

[10/12/2019, 7:09:30 PM] [Thermostat] Adding TCC Device Thermostat 5192195
[10/12/2019, 7:09:30 PM] [Thermostat] Initializing platform accessory 'Thermostat'...
[10/12/2019, 7:09:30 PM] [Thermostat] getServices Thermostat
Setup Payload:
X-HM://0023ISYWY4BJA
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
`

**Comment by naofireblade** [comment]
Thanks for commenting. What robot do you use?

**Comment by chrisaiello** [comment]
I've got the Botvac D3 Connected. As far as I understand it's very similar to the D4 and D5.

**Comment by naofireblade** [comment]
@maydaydarkhorse do you have the D3 as well?

**Comment by naofireblade** [comment]
@chrisaiello Do you have a floor plan saved in the map where you can set nogo lines?

**Comment by chrisaiello** [comment]
I’ve only had it for a couple days, so I haven’t set up the saved floor plan yet.

**Comment by naofireblade** [comment]
Ok then I know the problem and will fix it asap.

**Comment by maydaydarkhorse** [comment]
Hi guys, I have a D5 and no floor plan saved either.  I will see if adding a floorpan fixes anything.

**Comment by naofireblade** [comment]
Should be fixed in v0.7.1-beta.1
You can install the beta version with `npm install -g homebridge-neato@beta`

**Comment by chrisaiello** [comment]
Looks good so far, thanks for the quick fix! I’ll let you know if I experience any problems.

**Comment by naofireblade** [comment]
Great, thanks for the feedback!

**Comment by maydaydarkhorse** [comment]
Now my Robot shows up but I can not control it at all - Homekit says no response.

I can not find any home bridge log files anywhere.... But I get this error in home bridge after trying to activate the robot.

Cannot update robot. Check if robot is online. TypeError: Cannot read property 'width' of null
(node:938) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'width' of null
    at NeatoVacuumRobotAccessory.clean (/usr/lib/node_modules/homebridge-neato/accessories/neatoVacuumRobot.js:354:43)
    at platform.updateRobot (/usr/lib/node_modules/homebridge-neato/accessories/neatoVacuumRobot.js:255:12)
    at robot.device.getState (/usr/lib/node_modules/homebridge-neato/index.js:234:5)
    at Robot.<anonymous> (/usr/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:39:17)
    at /usr/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:506:17
    at /usr/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by naofireblade** [comment]
What version of the plugin do you use, 0.7.0 or 0.7.1-beta.1?

**Comment by naofireblade** [comment]
Did you try the spot cleaning or normal cleaning?

**Comment by maydaydarkhorse** [comment]
HI!  I am on 0.7.1-beta.1 ofter upgrading from 0.6.3 to 0.7.0-Beta.10 (Which I then had to google some sort of home bridge json instructions because the install was failing)

I have tried a spot clean and the robot will come off the dock and return to it. But it does nothing when I trigger a "House Clean"

**Comment by maydaydarkhorse** [comment]
This is what I had to do to get the -10 beta to install...

npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (pi) 
version: (1.0.0) 
description: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /home/pi/package.json:

{
  "name": "pi",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "node-botvac": "^0.4.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}


Is this OK? (yes) yes
pi@raspberrypi:~ $

**Comment by naofireblade** [comment]
@maydaydarkhorse That looks a bit strange. Usally you can uninstall and install packages (including betas) all day long.
However your bug should be fixed in v0.7.1-beta.2

**Comment by maydaydarkhorse** [comment]
G'day Again! That seems to have fixed it!

What was it? Was it because I don't have a map saved or something else?

**Comment by naofireblade** [comment]
Yes, the plugin had two consecutive bugs on robots without a map. It got pretty hard to integerate so many features with so many combinations of different robots and user setups. I’m glad it works now :) .

**Comment by naofireblade** [comment]
Released in v0.7.1
