### ISSUE TITLE
Added NPM to Homebridge unable to discover robots

### ISSUE THREAD

**Issue by schpeen** [naofireblade/homebridge-neato#48]
I added the NPM and I am using my correct email, and password but it cant seem to find my 2 Neato D7's. Any suggestions, or any steps I am missing. Any help is appreciated I am so anxious to try this. Thanks for taking time to make this. 

Joey

**Comment by naofireblade** [comment]
Can u assure that your homebridge is working? Do you have any other plugins successful running?
If so, can you access your homebridge log? The neato plugin writes log outputs if something went wrong while updating the robots.

**Comment by schpeen** [comment]
Well. I finally got it but thank you for the quick reply. My homebridge was working fine, and I was using the correct credentials to login. But I finally went to settings again and tried a few more times and then they finally showed up. Nice work on this it works great.

**Comment by naofireblade** [comment]
I'm glad to thear that :) .
