### ISSUE TITLE
unexpected error, Error getting robot meta information

### ISSUE THREAD

**Issue by symphil** [naofireblade/homebridge-neato#51]
Hi thank you for your effort to create this useful plugin
I have a neato D5, working well here, and my neato account and password both double checked.
here is the config:
    "platform": "NeatoVacuumRobot",
            "email": "*********@gmail.com",
            "password": "*************"

when running homebridge, all other plugins works well( yeelight and aqara)
but the error showed, and there are only 3 lines about neato:
[2/14/2020, 22:51:58] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[2/14/2020, 22:51:58] [NeatoVacuumRobot] Refresh is set to: auto
[2/14/2020, 22:52:03] [NeatoVacuumRobot] Error getting robot meta information: Error: Request failed with status code 404: null

no neato show in the homekit.

what is the problem? would you please help?

Thanks.

Phil

**Comment by naofireblade** [comment]
Hi Phil, does your neato is listed in your account?

https://www.neatorobotics.com/de/my-neato/

Can you try it again? Maybe the servers were offline for a few minutes.

**Comment by symphil** [comment]
Thanks for your reply!
Yes, the robot is in my account list, and it is the only one. 
also I can use Neato App to control it well.
I will try it again now.

**Comment by symphil** [comment]
No still the same...
[2/15/2020, 00:14:52] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[2/15/2020, 00:14:52] [NeatoVacuumRobot] Refresh is set to: auto
[NeatoVacuumRobot] Error getting robot meta information: Error: Request failed with status code 404: null

**Comment by symphil** [comment]
I just try to change my password to something simple and short one, try again, still the same error

**Comment by symphil** [comment]
tried many times, still the same problem 
Just try to use google home to add neato, and it works

**Comment by symphil** [comment]
@ghulands would you please help?

**Comment by symphil** [comment]
@naofireblade 
Hi Arne
Good day
I tried many times today, even changed my password in Neato website.
I also tried to removed my D5 robot and added again.
but still, it can not work, still showing the same info can not get the robot meta information.
I am stilling thinking what I can do, really wish I can fix this problem, hope with your help.
I am living in Shanghai, I also tried to use SSR to have my whole wifi connect to USA serve. still not work.
...............

**Comment by symphil** [comment]
just tried to change my neato account email address from symphil.yao@gmail.com to 36752188@qq.com. 
still appear the same problem can not get the robot meta information.

**Comment by symphil** [comment]
Dear Naofireblade
Still, not working, tried to created a new neato account and it still showing:
Error getting robot meta information: Error: Request failed with status code 404: null
would you please try to help.

Thanks.

Phil Yao

**Comment by symphil** [comment]
@naofireblade 
Hi I finally found the solution, here is the step, might help other user.
1. delete the robot from the neato account and app
2. re-add it into the neato account, make sure the robot name will be the same one add in the app later.
3. run homebridge with the plugin.
4. add the robot into the app. use the same robot name in the neato account.
then it will work.
if the neato already exist in the app and neato account, then run the homebridge, the plugin will not be able to find the robot. 
close the case...
