### ISSUE TITLE
Spot Size and Clean Twice not showing up with D7

### ISSUE THREAD

**Issue by ifeign** [naofireblade/homebridge-neato#52]
I saw you added features for spot size and clean twice, however I'm not seeing either of these features with my D7. I do have a switch for Spot Clean, but that is it. I only noticed because it cleaned a really small spot compared to when I do it with the Neato app.

Is there something I'm missing in my config? Currently it looks exactly like the example config.

I've completely uninstalled and reinstalled the plugin and it still looks like this screenshot.
<img width="661" alt="Screen Shot 2020-03-13 at 9 03 26 AM" src="https://user-images.githubusercontent.com/32289760/76638347-880ebe00-6509-11ea-863e-63c1c74456a4.png">

**Comment by ifeign** [comment]
Just realized I need a third party home app to adjust this. Could you specify this in the readme?

**Comment by naofireblade** [comment]
Thanks for the suggestion. Added it to the readme on github. Will be on npm in next release.
