### ISSUE TITLE
Error getting robot meta information 

### ISSUE THREAD

**Issue by Jodameister** [naofireblade/homebridge-neato#56]
Hello,
i get a error on startup the homebridge:
![87A71235-61F9-44BF-A2DF-7DF5EAB9A9A7](https://user-images.githubusercontent.com/55394372/90812649-bbf6d680-e326-11ea-8118-f67e9d609d12.jpeg)

I dont know when it begins. I noticed it since the robot vanished from HomeKit App.

Any idea?

**Comment by otabac** [comment]
Hi. 
sorry for raising it. 
I tried to readd it but has same error. 
I have Neato Connected vacuum

**Comment by naofireblade** [comment]
Will be fixed in #49
