### ISSUE TITLE
Multiple room cleaning

### ISSUE THREAD

**Issue by maschbaer** [naofireblade/homebridge-neato#57]
In your description you mention the feature „You can send the robot from one room to another as well. He will return to the base, wait there some seconds and then starts cleaning the next room.“

I habe a map of my home and defined several areas e.g kitchen, dining room, etc.
I then added a scene in Homekit which covers the according switches for cleaning the kitchen and the dining room...

However, the robot only cleans the first room and then returns to its base not continuing cleaning the next rooms...

I have a Neato D7, is there a special way how to set this up?

Regards,
Jan

**Comment by naofireblade** [comment]
The plug-in supports sending the robot to a room by using the switch. If the robot is currently cleaning a room it will go to the base and start cleaning the next room.
In your case you have to create a rather complex automation that starts cleaning the next room after the first one finishes,
