### ISSUE TITLE
Dock Sensor not working under iOS 11 beta

### ISSUE THREAD

**Issue by CooperCGN** [naofireblade/homebridge-neato#6]
Just to let you know, the plugin worked perfectly but with the latest iOS 11 beta I don't get the dock sensors to trigger. My two robots definitely are online, as I can start them from the home app on my iPad. Is there any way to check if it's on my side? Other sensors like motion and door are still doing their job as expected.

**Comment by naofireblade** [comment]
Hello CooperCGN,

homekit seems to be very unstable in the iOS beta versions. What device are you using as your homekit hub? Make sure, that this one is also on iOS 11. Also removing and re-adding the hub to homekit might help.

Do you see the correct state when you manually refresh the robot in the elgato eve app (pulling down)?

**Comment by CooperCGN** [comment]
Hi,

I'm actually running the latest betas on all my devices including my Apple TV4 as home hub. The state isn't updated in the eve app either when manually refreshing. Battery state is processed the right way, it's only the dock thats not working. I wonder if Neato changed anything in the API as they just updated the iOS app and introduced the D7 at IFA.

I'm going to setup a separate Homebridge service tomorrow with only the neato plugin activated to see if there's something unusual in the logs. Any suggestions what to look for? Are there any entries for  docking or undocking when data is pulled from the neato cloud?

**Comment by CooperCGN** [comment]
Just checked the log again and it definitely shows two different entries for docked and not docked:
Sep 03 18:54:17 raspberrypi homebridge[2398]: Sun, 03 Sep 2017 16:54:17 GMT homebridge-neato Erdgeschoss: Is docked: true
Sep 03 19:00:58 raspberrypi homebridge[2398]: Sun, 03 Sep 2017 17:00:58 GMT homebridge-neato Erdgeschoss: Is docked: false

So I assume it's either a HomeKit problem or Apple changed something which causes a problem with homebridge

**Comment by naofireblade** [comment]
Ok good to know that. Maybe it's a problem with the underlying HAP-NodeJS. I will look into that as soon as iOS 11 is released.

**Comment by CooperCGN** [comment]
Have a look at this issue with homebridge: https://github.com/nfarina/homebridge/issues/1468
I tried going back to 0.4.22 but that crashes my homebridge-hue installation, the sensors are working with 0.4.22, so it's in the homebridge code.

**Comment by naofireblade** [comment]
Indeed, I have the same problem after updating homebridge. Still running on iOS 10.

**Comment by CooperCGN** [comment]
I went back to the hue plugin version that works under 0.4.22, guess we will have to wait till nfarina gets this fixed, at least the sensors are working again, as I need them in some rules.

**Comment by naofireblade** [comment]
I found the problem. The sensor state must be 1/0 now and no longer true/false. I published a fix in verson 0.4.5 to npm.

**Comment by naofireblade** [comment]
I found the problem and fixed it in release

**Comment by naofireblade** [comment]
Is it working for you as well?

**Comment by CooperCGN** [comment]
Just installed it and yes it works for me as well, perfect. Thanks!

**Comment by naofireblade** [comment]
Great to hear that.
