### ISSUE TITLE
Neato switches appear in default room regular

### ISSUE THREAD

**Issue by DJay-X** [naofireblade/homebridge-neato#63]
Hi @naofireblade I hope you are doing well.

I noticed that for whatever reason all the neato switches are getting moved to default room from time to time.

I have no Idea what the reason is. It's only with the neato Plugin. 🤷🏼‍♂️
It's of course inconvenient because of the Names are back to default as well and all automation are lost.

There shout be nothing strange with my homebridge v1.3.4 hb-service, Node v14.16.1, npm v7.10.0. 

Speicherpfad | /var/lib/homebridge
Konfigurationspfad | /var/lib/homebridge/config.json

Everything is running great.
It happens not always after a reboot, or updating homebridge node etc. I can't find a correlation.
Any other devices and plugins stay as they are the entire time.

Do you have any idea?

Thanks in advance for your time and help. 👍

**Comment by naofireblade** [comment]
This is a known big issue with my plugin. When the neato servers are offline the robot somehow gets deleted. I'm planning a complete rewrite of the plugin to fix the issue.

**Comment by naofireblade** [comment]
Will continue to work on this in the old issue: https://github.com/naofireblade/homebridge-neato/issues/44
