### ISSUE TITLE
Multipule neatos

### ISSUE THREAD

**Issue by bricebauman** [naofireblade/homebridge-neato#9]
Can this plug in handle multiple neatos? If so how do I configure it?

Thanks

**Comment by naofireblade** [comment]
Yes it can. You just configure your neato account and all neatos in this account will be accessible automatically. If you have them in different accounts, please transfer them to one account.

Best regards
Arne

**Comment by doublehache** [comment]
Hello @naofireblade 
I tying to link my 2 robots (D7 and D9) but can't manage to..
the log said 
[4/19/2023, 2:47:08 PM] [homebridge-neato] Found robot #1 named "Machine" with serial "GPC44119-XXXXXXXXXXXX"
[4/19/2023, 2:47:08 PM] [homebridge-neato] Added cleaning device named: Machine
This one (D7) is managed by the Neato app
The other (D9) managed by MyNeato App - not found but the plugin. 
Is there something I can do? 
Regards,

**Comment by naofireblade** [comment]
Sadly not. Neato does not provide an API for newer models.
